apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: credit-fraud-inference
  namespace: ml-inference
  labels:
    app: credit-fraud-inference
spec:
  selector:
    matchLabels:
      app: credit-fraud-inference
  namespaceSelector:
    matchNames:
      - ml-inference
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
