apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: credit-fraud-inference
  namespace: ml-inference
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 250m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /predict
            pathType: Prefix
            backend:
              service:
                name: credit-fraud-inference
                port:
                  number: 3000
