apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-fraud-inference-green
  namespace: ml-inference
  labels:
    app: credit-fraud-inference
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credit-fraud-inference
      color: green
  template:
    metadata:
      labels:
        app: credit-fraud-inference
        color: green
    spec:
      serviceAccountName: credit-fraud-inference-green-sa
      containers:
        - name: inference
          image: 581212334853.dkr.ecr.eu-west-1.amazonaws.com/yas-ml-inference:backend-final-v7
          imagePullPolicy: Always
          env:
            - name: BENTO_S3_BUCKET
              value: mlops-model-store-prod
            - name: BENTO_S3_PREFIX
              value: bentoml/models
            - name: BENTOML_MODEL_STAGE
              value: CANDIDATE
            - name: BENTOML_HOME
              value: /tmp/bentoml
          ports:
            - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
