apiVersion: v1
kind: ServiceAccount
metadata:
  name: credit-fraud-inference-green-sa
  namespace: ml-inference
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::581212334853:role/credit-fraud-inference-green-irsa
