apiVersion: v1
kind: Service
metadata:
  name: credit-fraud-inference
  namespace: ml-inference
spec:
  selector:
    app: credit-fraud-inference
    color: blue
  ports:
    - name: http
      port: 3000
      targetPort: 3000
