replicaCount: 1

image:
  repository: ghcr.io/example/ml-inference
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  name: credit-fraud-inference
  annotations: {}

service:
  port: 3000

activeColor: green

env:
  MODEL_BUCKET: ""
  MODEL_POINTER_KEY: ""

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
